### ISSUE TITLE
Post Issue - Failed to login

### ISSUE THREAD

**Issue by chrisjackr** [JohannDickson/puregym-tools#1]
Hi, I attempted to code something similar to this a while ago but got stuck on posting the webpage request with email, password and token - I seem to reach the same issues when attempting to log in with your code ("failed to login"). The token is definitely being retrieved correctly and my username/password are valid. Any thoughts on what might be the problem? Thanks

**Comment by JohannDickson** [comment]
It looks like the login process has changed a bit.

By rerunning my same code I can see after login I get a cloudflare page with `error 1020` asking me to enable cookies, but they already should be through use of the `requests.Session()`

Having looked at the workflow in a browser, the `LOGIN_API` URL has changed to https://auth.puregym.com/account/login and the form data has changed.. The process seems a bit more complicated now.

I'll see if I can fix this.

**Comment by JohannDickson** [comment]
@chrisjackr I've managed to fix the login process on the `fix/login` branch, but since I'm no longer a member of puregym I can't check that the activity / people counter workflows are still valid.. would you be able to test those for me?
